dependencies {
    api "io.netty:netty-all:${nettyVersion}"
    api "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
    implementation 'org.xerial.snappy:snappy-java:1.1.10.8'
    implementation 'at.yawk.lz4:lz4-java:1.11.2'

    compileOnly 'io.micrometer:micrometer-core:1.17.0'
    testImplementation 'io.micrometer:micrometer-core:1.17.0'

    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'org.postgresql:postgresql:42.7.5'
    testImplementation 'com.mysql:mysql-connector-j:9.1.0'
    testRuntimeOnly 'ch.qos.logback:logback-classic:1.5.38'
}
